version: '3'
services:
  postgres:
    image: postgres
    networks:
    - ohdsi
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  impala:
    build: ./impala
    image: ohdsi-hadoop-impala
    networks:
    - ohdsi
    external_links:
    - postgres
    volumes:
    - ./cdmv5vocab:/data/cdmv5vocab
    - ./synpuf:/data/synpuf
    environment:
      PGPASSWORD: postgres
    ports:
    # HDFS
    - 50070:50070
    - 50075:50075
    - 8020:8020
    - 8042:8042
    # Hive
    - 9083:9083
    # Impala
    - 21000:21000
    - 21050:21050
    - 25000:25000
    - 25010:25010
    - 25020:25020
networks:
  default:
    external:
      name: ohdsi
  ohdsi:
    driver: bridge